require("core.keymappings")
require("core.configs")


require("plugins.paker-plugin")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.tokyonight")
require("plugins.bufferline")
require("plugins.nvim-tmux-nav")
require("plugins.lsp.mason")
require("plugins.lsp.lsp-config")
require("plugins.lsp.cmp")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.gitsigns")
